create table if not exists categories (
  slug text primary key,
  name text not null,
  color text not null
);

create table if not exists articles (
  id bigint primary key,
  slug text,
  title text not null,
  category text not null,
  excerpt text not null,
  lead text,
  content jsonb not null,
  image text,
  cover_image text,
  image_caption text,
  image_credit text,
  tags jsonb not null default '[]'::jsonb,
  author text not null,
  author_slug text,
  author_role text,
  date date not null,
  created_at timestamptz not null default now()
);

create table if not exists sources (
  id text primary key,
  name text not null,
  url text not null,
  category text,
  color text,
  notice text
);

insert into categories (slug, name, color) values ('politik','Politik','#c8102e') on conflict (slug) do nothing;
insert into categories (slug, name, color) values ('ekonomi','Ekonomi','#1a5c8a') on conflict (slug) do nothing;
insert into categories (slug, name, color) values ('nasional','Nasional','#2e7d32') on conflict (slug) do nothing;

insert into articles (id, title, category, excerpt, content, image, tags, author, author_slug, author_role, date) values (89, 'Harga Beras Stabil Jelang Panen Raya, Bulog Siapkan Serapan Gabah', 'Ekonomi', 'Stok CBP aman, pemerintah antisipasi kenaikan harga di masa paceklik dengan serapan lebih awal.', '["JAKARTA — Stok beras pemerintah pada September 2026 tercatat stabil dengan Cadangan Beras Pemerintah (CBP) di angka aman. Harga gabah kering panen di tingkat petani mulai turun seiring masuknya masa panen raya di sejumlah daerah sentra.", "Kepala Divisi Regional Bulog menyatakan pihaknya siap menyerap gabah sesuai Harga Pembelian Pemerintah (HPP) untuk menjaga harga di tingkat petani tetap menguntungkan. \"Kami buka titik serap di 12 provinsi sentra produksi,\" ujarnya.", "Pemerintah juga mengingatkan agar ketersediaan stok menjelang akhir tahun tetap terjaga. Operasi pasar dilakukan secara berkala di pasar-pasar tradisional untuk meredam potensi kenaikan harga.", "Pengamat pertanian menilai langkah serapan lebih awal ini tepat untuk mengamankan pasokan saat masa paceklik. Namun ia mengingatkan soal kesinambungan program agar harga gabah tidak jatuh terlalu dalam di musim panen raya."]'::jsonb, '/images/articles/beras-stabil-jelang-panen-bulog.jpg', '["Pangan", "Beras", "Bulog", "Pertanian"]'::jsonb, 'Aulia Rahman', 'aulia-rahman', 'Jurnalis Ekonomi', '2026-09-12') on conflict (id) do nothing;
insert into articles (id, title, category, excerpt, content, image, tags, author, author_slug, author_role, date) values (121, 'Harga Emas Antam Naik ke Rp1,7 Juta per Gram, Sempat Rebutan Antrean', 'Ekonomi', 'Investor beralih ke logam mulia sebagai aset aman di tengah ketidakpastian pasar global.', '["JAKARTA — Harga emas batangan Antam naik menyentuh Rp1,7 juta per gram pada perdagangan akhir pekan. Antrean pembeli sempat mengular di sejumlah butik logam mulia di Jakarta dan Surabaya.", "Kenaikan ini dipicu kekhawatiran pelaku pasar terhadap eskalasi ketegangan dagang global dan pelemahan dolar AS. Logam mulia kembali menjadi pilihan utama investor dalam mencari aset aman.", "Analis komoditas menilai tren penguatan emas masih berlanjut hingga akhir tahun. Ia menyarankan investor tetap memperhatikan harga jual kembali (buyback) yang juga ikut naik mengikuti harga dasar.", "Bagi pembeli yang ingin berinvestasi, pengamat mengingatkan pentingnya membeli melalui lembaga resmi dan menyimpan bukti transaksi untuk menjamin kemudahan penjualan kembali di kemudian hari."]'::jsonb, '/images/articles/emas-antam-rp1-7-juta-per-gram.jpg', '["Emas", "Antam", "Investasi", "Logam Mulia"]'::jsonb, 'Siti Nurhaliza', 'siti-nurhaliza', 'Jurnalis Ekonomi', '2026-09-12') on conflict (id) do nothing;
insert into articles (id, title, category, excerpt, content, image, tags, author, author_slug, author_role, date) values (100, 'Pemerintah Percepat Vaksinasi Booster Kedua untuk Tenaga Kesehatan', 'Kesehatan', 'Nakes pertama yang divaksin, menyusul lansia dan kelompok rentan pada tahap berikutnya.', '["JAKARTA — Pemerintah memulai program vaksinasi booster kedua secara bertahap, dengan tenaga kesehatan (nakes) sebagai prioritas pertama. Langkah ini untuk menjaga kekebalan kelompok yang paling rentan terdampak.", "Kementerian Kesehatan menyatakan vaksin yang digunakan telah melalui kajian keamanan dan efektivitas. Dosis akan didistribusikan ke puskesmas dan rumah sakit rujukan di seluruh provinsi.", "Setelah nakes, giliran lansia dan penyandang komorbid yang akan menerima booster. Pemerintah mengimbau masyarakat tetap mematuhi protokol kesehatan meski cakupan vaksinasi sudah tinggi.", "Epidemiolog menilai kebijakan ini tepat dilakukan menjelang musim hujan. Ia menekankan pentingnya memperbarui data penerima vaksin agar cakupan bisa dipantau secara akurat."]'::jsonb, '/images/articles/vaksinasi-booster-kedua-nakes.jpg', '["Vaksin", "Kesehatan", "Nakes", "Booster"]'::jsonb, 'dr. Bambang Permadi', 'bambang-permadi', 'Kontributor Kesehatan', '2026-09-11') on conflict (id) do nothing;
insert into articles (id, title, category, excerpt, content, image, tags, author, author_slug, author_role, date) values (77, 'Gunung Merapi Siaga, Warga Lereng Diminta Waspadai Awan Panas', 'Nasional', 'Aktivitas vulkanik meningkat, radius aman diperpanjang hingga lima kilometer dari puncak.', '["YOGYAKARTA — Status Gunung Merapi dinaikkan menjadi Siaga (Level III) menyusul meningkatnya aktivitas vulkanik yang terpantau dalam beberapa hari terakhir. Guguran lava pijar dan awan panas teramati mengarah ke barat daya.", "Balai Penyelidikan dan Pengembangan Teknologi Kebencanaan Geologi (BPPTKG) memperpanjang radius aman hingga lima kilometer dari puncak. Warga di lereng diimbau tidak beraktivitas di dalam zona bahaya.", "BPBD setempat telah menyiapkan pos pengungsian dan jalur evakuasi. Warga yang tinggal di sekitar bantaran sungai yang berhulu di Merapi diminta waspada terhadap potensi lahar saat hujan.", "Masyarakat diimbau tetap tenang namun waspada, dan hanya mengikuti informasi resmi dari BPPTKG serta BPBD. Jalur pendakian ke puncak Merapi ditutup sementara."]'::jsonb, '/images/articles/merapi-siaga-waspada-awan-panas.jpg', '["Merapi", "Bencana", "Vulkanologi", "Yogyakarta"]'::jsonb, 'Redaksi GentaNusa', 'redaksi-generic', 'Redaktur GentaNusa', '2026-09-11') on conflict (id) do nothing;
insert into articles (id, title, category, excerpt, content, image, tags, author, author_slug, author_role, date) values (55, 'PSSI Perpanjang Kerja Sama dengan Pelatih Baru hingga Piala Asia 2027', 'Olahraga', 'Kontrak diperpanjang setelah sederet hasil positif di kualifikasi, target lolos babak utama.', '["JAKARTA — PSSI resmi memperpanjang kerja sama dengan pelatih tim nasional hingga berakhirnya Piala Asia 2027. Keputusan ini diambil setelah tim menunjukkan konsistensi permainan pada babak kualifikasi.", "Sekretaris Jenderal PSSI menyatakan perpanjangan kontrak merupakan bentuk apresiasi atas perkembangan tim. \"Kami ingin membangun kesinambungan program pembinaan,\" ujarnya dalam konferensi pers.", "Pelatih menyambut baik kepercayaan ini dan menyebut target utama adalah membawa tim lolos ke babak utama serta bersaing di level Asia. Ia berencana melakukan pemusatan latihan dan uji coba internasional.", "Ia juga menekankan pentingnya regenerasi pemain muda dengan memperbanyak menit bermain bagi talenta lokal di kompetisi domestik."]'::jsonb, '/images/articles/pssi-perpanjang-kerja-sama-pelatih.jpg', '["PSSI", "Timnas", "Piala Asia", "Sepak Bola"]'::jsonb, 'Rizki Pratama', 'rizki-pratama', 'Jurnalis Olahraga', '2026-09-10') on conflict (id) do nothing;
insert into articles (id, title, category, excerpt, content, image, tags, author, author_slug, author_role, date) values (45, 'Menteri Kehutanan Tegaskan Moratorium Izin Baru Tetap Berlaku', 'Nasional', 'Kawasan hutan lindung dan gambut dilarang untuk aktivitas baru, izin lama di audit.', '["JAKARTA — Menteri Kehutanan menegaskan moratorium pemberian izin baru di kawasan hutan lindung dan lahan gambut tetap berlaku. Kebijakan ini merupakan komitmen pemerintah dalam menekan deforestasi.", "Penegasan ini menyusul sejumlah usulan dari daerah agar sebagian kawasan dibuka kembali. Pemerintah memilih mengedepankan aspek keberlanjutan lingkungan jangka panjang.", "Izin yang sudah terbit sebelumnya akan diaudit untuk memastikan tidak ada pelanggaran. Jika ditemukan penyimpangan, sanksi akan dijatuhkan sesuai peraturan perundang-undangan.", "Direktur eksekutif lembaga lingkungan menilai sikap pemerintah ini sebagai sinyal positif. Pelaku usaha diharapkan menyelaraskan kegiatan dengan prinsip kelestarian agar tidak melanggar aturan."]'::jsonb, '/images/articles/moratorium-izin-hutan-tetap-berlaku.jpg', '["Kehutanan", "Moratorium", "Lingkungan", "Gambut"]'::jsonb, 'Redaksi GentaNusa', 'redaksi-generic', 'Redaktur GentaNusa', '2026-09-09') on conflict (id) do nothing;

insert into sources (id, name, url, category, color, notice) values ('antara-ekonomi', 'Antara Ekonomi', 'https://www.antaranews.com/rss/ekonomi', 'Ekonomi', '#c8102e', 'Konten ditautkan dari Antara News. Semua hak cipta milik penyedia sumber.') on conflict (id) do nothing;
insert into sources (id, name, url, category, color, notice) values ('antara-terkini', 'Antara Terkini', 'https://www.antaranews.com/rss/terkini', 'Nasional', '#1a5c8a', 'Konten ditautkan dari Antara News. Semua hak cipta milik penyedia sumber.') on conflict (id) do nothing;
insert into sources (id, name, url, category, color, notice) values ('cnbc-indonesia', 'CNBC Indonesia', 'https://www.cnbcindonesia.com/rss', 'Ekonomi', '#f0a500', 'Konten ditautkan dari CNBC Indonesia. Semua hak cipta milik penyedia sumber.') on conflict (id) do nothing;
insert into sources (id, name, url, category, color, notice) values ('cnn-indonesia', 'CNN Indonesia', 'https://www.cnnindonesia.com/rss', 'Nasional', '#c8102e', 'Konten ditautkan dari CNN Indonesia. Semua hak cipta milik penyedia sumber.') on conflict (id) do nothing;
insert into sources (id, name, url, category, color, notice) values ('tribunnews', 'Tribunnews', 'https://www.tribunnews.com/rss', 'Nasional', '#2e7d32', 'Konten ditautkan dari Tribunnews. Semua hak cipta milik penyedia sumber.') on conflict (id) do nothing;